version: '3'

services:
  clipeflixpg:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'clipeflixpg'
    restart: always
    volumes:
      - clipeflixpg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgsenha

volumes:
  clipeflixpg-data: